version: '3.7'
services:
  opensearch_master1:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    container_name: master1
    hostname: master1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./master1/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
    ports:
      # - target: 9200
      #   published: 9200
      #   protocol: tcp
      #   mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    
  opensearch_data1:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    container_name: data1
    hostname: data1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data1/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == manager]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
    
  opensearch_data2:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    container_name: data2
    hostname: data2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data2/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == worker]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
    
  opensearch_data3:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    container_name: data3
    hostname: data3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data3/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == manager]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
    
  opensearch_data4:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    container_name: data4
    hostname: data4
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data4:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == worker]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
       - bubo_op
    
  opensearch_coordinate:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    container_name: coordinate
    hostname: coordinate
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./coordinate:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == worker]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
    
  opensearch-dashboards:
    restart: always
    image: opensearchproject/opensearch-dashboards:2.2.0
    environment:
      OPENSEARCH_HOSTS: https://data1:9200
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    networks:
      - bubo_op
    deploy:
      endpoint_mode: dnsrr
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    configs:
    - source: opensearch-dashboards.yml
      target: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    volumes:
      - "./certs:/usr/share/opensearch-dashboards/config/certificates"

  logstash:
    restart: always
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.3
    networks:
      - bubo_op
    ports:
      - target: 5044
        published: 5044
        protocol: tcp
        mode: host
    environment:
      LS_JAVA_OPTS: -Xmx2g -Xms2g
    deploy:
      endpoint_mode: dnsrr 
      mode: "replicated"
      replicas: 1
    configs:
      - source: process_ioc.rb
        target: /usr/share/logstash/process_ioc.rb
    volumes:
      - "./logstash/patterns.d/:/usr/share/logstash/patterns.d/"
      - "./pipeline/:/usr/share/logstash/pipeline/"
    depends_on:
       - data2

  memcached:
    restart: always
    container_name: memcached
    image: bubocyber/memcached:latest
    build: .
    ports:
      - target: 11211
        published: 11211
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op

  misp2memcached:
    restart: always
    container_name: misp2memcached
    build: .
    image: bubocyber/misp2memcached:latest
    networks:
      - bubo_op
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1

  visualizer:
    restart: always
    image: dockersamples/visualizer
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]      
      
networks:
  bubo_op:
    driver: overlay
    name: bubo_op

volumes:
  master1:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/master1"
      password: bubo
  data1:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/data1"
      password: bubo
  data2:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/data2"
      password: bubo
  data3:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/data3"  
      password: bubo
  data4:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/data4"  
      password: bubo
  coordinate:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/coordinate"
      password: bubo
  certs:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/certs"  
      password: bubo
  logstash:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/logstash/patterns.d"  
      password: bubo
  pipeline:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "admin-bubo@10.1.1.42:/home/admin-bubo/bubo_cert_prod_v3/pipeline/pipeline.conf"  
      password: bubo

configs:
  process_ioc.rb:
    file: ./process_ioc.rb
  opensearch.yml:
    file: ./opensearch.yml
  jvm.options:
    file: ./jvm.options
  opensearch-dashboards.yml:
    file: ./opensearch-dashboards.yml