version: '3.7'
services:
  opensearch_master1:
    restart: always
    image: opensearchproject/opensearch:2.11.1
    container_name: master1
    hostname: master1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./master1/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
#           - "./script/:/usr/share/opensearch/script"
      - "./internal_user.yml:/config/opensearch-security/internal_users.yml"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == manager]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
#     command: ["sh", "-c", "./script/opensearch-docker-entrypoint.sh"]

  opensearch_data1:
    restart: always
    image: opensearchproject/opensearch:2.11.0
    container_name: data1
    hostname: data1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data1/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
#           - "./script/:/usr/share/opensearch/script"
      - "./internal_user.yml:/config/opensearch-security/internal_users.yml"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.hostname == worker]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
#     command: ["sh", "-c", "./script/opensearch-docker-entrypoint.sh"]
    
  opensearch_data2:
    restart: always
    image: opensearchproject/opensearch:2.11.0
    container_name: data2
    hostname: data2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data2/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
#           - "./script/:/usr/share/opensearch/script"
      - "./internal_user.yml:/config/opensearch-security/internal_users.yml"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == manager]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
#     command: ["sh", "-c", "./script/opensearch-docker-entrypoint.sh"]
   
  opensearch_data3:
    restart: always
    image: opensearchproject/opensearch:2.11.0
    container_name: data3
    hostname: data3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data3/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
#           - "./script/:/usr/share/opensearch/script"
      - "./internal_user.yml:/config/opensearch-security/internal_users.yml"
    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.role == manager]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
#     command: ["sh", "-c", "./script/opensearch-docker-entrypoint.sh"]
    
  opensearch_data4:
    restart: always
    image: opensearchproject/opensearch:2.11.0
    container_name: data4
    hostname: data4
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./data4/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch./config/certificates"
#           - "./script/:/usr/share/opensearch/script"
      - "./internal_user.yml:/config/opensearch-security/internal_users.yml"

    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.hostname == worker]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
       - bubo_op
#     command: ["sh", "-c", "./script/opensearch-docker-entrypoint.sh"]
    
  opensearch_coordinate:
    restart: always
    image: opensearchproject/opensearch:2.11.0
    container_name: coordinate
    hostname: coordinate
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./coordinate/:/usr/share/opensearch/data/"
      - "./certs:/usr/share/opensearch/config/certificates"
#           - "./script/:/usr/share/opensearch/script"
      - "./internal_user.yml:/config/opensearch-security/internal_users.yml"

    configs:
      - source: opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - source: jvm.options
        target: /usr/share/opensearch/config/jvm.options
    deploy:
      placement:
        constraints: [node.hostname == worker]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op
#     command: ["sh", "-c", "./script/opensearch-docker-entrypoint.sh"]
    
  opensearch-dashboards:
    restart: always
    image: opensearchproject/opensearch-dashboards:2.11.0
    environment:
      OPENSEARCH_HOSTS: '["https://data1:9200","https://data2:9200","https://data3:9200","https://data4:9200"]'
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    ports:
      - 5601:5601
    networks:
      - bubo_op
    deploy:
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    configs:
    - source: opensearch-dashboards.yml
      target: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    volumes:
      - "./certs:/usr/share/opensearch-dashboards/config/certificates"

  logstash:
    restart: always
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.4.0
    container_name: logstash1
    networks:
      - bubo_op
    ports:
      - 5044:5044
#      - 9304:9304
    environment:
      LS_JAVA_OPTS: -Xmx6g -Xms6g
      pipeline.id: main
      path.config: /usr/share/logstash/pipeline/*.conf
      pipeline.batch.size: 1000
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints: [node.hostname == swarm3]
    configs:
      - source: process_ioc.rb
        target: /usr/share/logstash/process_ioc.rb
    volumes:
      - "./logstash_pipeline/:/usr/share/logstash/pipeline/"

  memcached:
    restart: always
    container_name: memcached
    image: bubocyber/memcached:latest
    build: .
    ports:
      - target: 11211
        published: 11211
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
    networks:
      - bubo_op

  misp2memcached:
    restart: always
    container_name: misp2memcached
    build: .
    image: bubocyber/misp2memcached_internal:interne
    networks:
      - bubo_op
    deploy:
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1

  visualizer:
    restart: always
    image: dockersamples/visualizer
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]      
      
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - "./prometheus:/etc/prometheus"
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   networks:
  #     - bubo_op

networks:
  bubo_op:
    driver: overlay
    name: bubo_op

volumes:
   master1 :
     driver: local
   data1 :
     driver: local
   data2 :
     driver: local
   data3 :
     driver: local
   data4 :
     driver: local
   coordinate :
     driver: local

configs:
  process_ioc.rb:
    file: ./process_ioc.rb
  opensearch.yml:
    file: ./opensearch.yml
  jvm.options:
    file: ./jvm.options
  opensearch-dashboards.yml:
    file: ./opensearch-dashboards.yml
