global:
  scrape_interval: 15s

scrape_configs:
  - job_name: opensearch
    scheme: https
    scrape_interval: 10s
    metrics_path: "/_prometheus/metrics"
    static_configs:
      - targets:
        - data1:9200
        - master1:9200
        - data2:9200
        - data3:9200
        - data4:9200
        - coordinate:9200
    basic_auth:
      username: admin
      password: admin
    tls_config:
      insecure_skip_verify: true